apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.name | lower }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.service.name | lower }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name | lower }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        - name: {{ .name }}
        {{- end }}
      {{- end }}
      containers:
      - name: {{ .Values.service.name | lower }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.port }}
        envFrom:
        - secretRef:
            name: app-env  # ✅ Load .env variables from the Kubernetes secret
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
