name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: latest

      - name: Package Helm Chart
        run: |
          mkdir -p .cr-release-packages
          helm package charts/HelmIngressKit --destination .cr-release-packages

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Commit and Push to gh-pages
        run: |
          git fetch origin gh-pages
          git checkout gh-pages || git checkout --orphan gh-pages
          mkdir -p docs
          mv .cr-release-packages/* docs/
          helm repo index docs --url https://helmingresskit.amitdalal.com/
          git add docs/
          git commit -m "Update Helm chart repository index"
          git push origin gh-pages
